name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h UTC
  workflow_dispatch:

jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |-
            --format sarif
            --output _.sarif
            ./app 

        
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: _.sarif

  sourcecode-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep (Java ruleset)
        run: semgrep --config=p/java --sarif --output=results.sarif .

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif